<?php
/**
   * @var Amasty\UserName\Block\Username $cssClass
  *  @var Amasty\UserName\Block\Username $block
 */
?>
<div class="formClass">
    <form class="myForm" name="feedback" method="POST" action="/">
        <div class="<?= $cssClass = $block->hasCssClassSignature() ? ' ' . $block->getCssClassSignature() : ''; ?>">
            It's my form
        </div>

        <div class="<?= $cssClass = $block->hasCssClassSku() ? ' ' . $block->getCssClassSku() : ''; ?>">
            SKU
            <input  type="text" name="sku" required="required">
        </div>

        <div class="<?= $cssClass = $block->hasCssClassQty() ? ' ' . $block->getCssClassQty() : ''; ?>">
            Quantity
            <input type="number" name="qty" required="required">
        </div>

        <?= $block->getChildHtml() ?>

        <div class="submit_btn">
            <input type="submit" name="submit_btn" value="Отправить">
        </div>
    </form>
</div>
