<?php
/**
   * @var Amasty\UserName\Block $block
 */
?>
<div class="formClass">
    <form class="myForm" name="feedback" method="POST" action="/mypage/usernameform/usernameform" data-mage-init='{
    "validation":
        {"rules":
            {"qty":
                {"required":true, "min":0, "type":"number"}
            }
        }}'>
        <div class="<?= $cssClass = $block->hasCssClassSignature() ? ' ' . $block->getCssClassSignature() : ''; ?>">
            It's my form
        </div>

        <div data-bind="scope: 'skuAutocomplete'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>

        <?php if ($block->getIsShowQty()): ?>
        <div class="<?= $cssClass = $block->hasCssClassQty() ? ' ' . $block->getCssClassQty() : ''; ?>">
            Quantity
            <input type="number" name="qty" value="<?= $block->getQty() ?: ''; ?>">
        </div>
        <?php endif; ?>

        <?= $block->getChildHtml() ?>

        <div class="submit_btn">
            <input type="submit" name="submit_btn" value="Отправить">
        </div>
    </form>
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "skuAutocomplete": {
                       "component": "Amasty_UserName/js/koAutocomplete",
                       "template" : "Amasty_UserName/koAutocomplete"
                   }
               }
           }
       }
   }
</script>