<?php
/**
   * @var Amasty\UserName\Block $block

 */
?>
<div class="formClass">
    <form class="myForm" name="feedback" method="POST" action="/">
        <div class="<?= $cssClass = $block->hasCssClassSignature() ? ' ' . $block->getCssClassSignature() : ''; ?>">
            It's my form
        </div>


        <div class="<?= $cssClass = $block->hasCssClassSku() ? ' ' . $block->getCssClassSku() : ''; ?>">
            SKU
            <input  type="text" name="sku" required="required">
        </div>

        <?php if ($block->getIsShowQty()): ?>
        <div class="<?= $cssClass = $block->hasCssClassQty() ? ' ' . $block->getCssClassQty() : ''; ?>">
            Quantity
            <input type="number" name="qty" required="required" value="<?= $block->getQty() ?: ''; ?>">
        </div>
        <?php endif; ?>

        <?= $block->getChildHtml() ?>

        <div class="submit_btn">
            <input type="submit" name="submit_btn" value="Отправить">
        </div>
    </form>
</div>
